#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __old_compatible {

    umask ${UMASK}

    if [ -f /config/bangumi.json ]; then
        mv /config/bangumi.json /app/data/bangumi.json
    fi

}

__old_compatible 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"