name: 问题反馈
description: File a bug report
title: "[错误报告] 请在此处简单描述你的问题"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        描述问题前，请先更新到最新版本。2.5 之前的版本升级请参考 [升级指南](https://github.com/EstrellaXD/Auto_Bangumi/wiki/2.6更新说明#如何从老版本更新的注意事项)
        请确认以下信息，如果你的问题可以直接在文档中找到，那么你的 issue 将会被直接关闭。
        解析器问题请转到[专用模板](https://github.com/EstrellaXD/Auto_Bangumi/issues/new?assignees=&labels=bug&template=parser_bug.yml&title=%5B解析器错误%5D)，
        重命名问题请到[专用模板](https://github.com/EstrellaXD/Auto_Bangumi/issues/new?assignees=&labels=bug&template=rename_bug.yml&title=%5B重命名错误%5D)
  - type: checkboxes
    id: ensure
    attributes:
      label: 确认
      description: 在提交 issue 之前，请确认你已经阅读并确认以下内容
      options:
        - label: 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
          required: true
        - label: 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/FAQ)，确保提出的问题不在其中。
          required: true
        - label: 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
          required: true
        - label: 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
          required: true
        - label: 我已经修改标题，将标题中的 描述 替换为我遇到的问题。
          required: true
  - type: input
    id: version
    attributes:
      label: 当前程序版本
      description: 遇到问题时程序所在的版本号
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 问题类型
      description: 你在以下哪个部分碰到了问题
      options:
        - WebUI
        - 程序运行问题
        - 其他问题
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: 请详细描述你碰到的问题
      placeholder: "问题描述"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 发生问题时系统日志
      description: 问题出现时，程序运行日志请复制到这里。
      render: bash