name: 项目讨论
description: discussion
title: "[Discussion]: "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        [BUG](https://github.com/EstrellaXD/Auto_Bangumi/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D%3A) 与 [Feature Request](https://github.com/EstrellaXD/Auto_Bangumi/issues/new?assignees=&labels=feature+request&template=feature_request.yml&title=%5BFeature+Request%5D%3A+) 请转到对应位置提交。
  - type: textarea
    id: discussion
    attributes:
      label: 项目讨论
      description: 请详细描述需要讨论的内容。
      placeholder: "项目讨论"
    validations:
      required: true