version: '3.3'
services:
  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - TIME=1800
      - HOST=localhost:8080
      - USER=admin
      - PASSWORD=adminadmin
      - METHOD=pn
      - GROUP_TAG=True
      - NOT_CONTAIN=720
      - DOWNLOAD_PATH=${DOWNLOAD_PATH}
      - RSS=${RSS}
    networks:
      - auto_bangumi
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest

networks:
  auto_bangumi:
