/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbAdd: typeof import('./../../src/components/basic/ab-add.vue')['default']
    AbAddRss: typeof import('./../../src/components/ab-add-rss.vue')['default']
    AbBangumiCard: typeof import('./../../src/components/ab-bangumi-card.vue')['default']
    AbButton: typeof import('./../../src/components/basic/ab-button.vue')['default']
    AbChangeAccount: typeof import('./../../src/components/ab-change-account.vue')['default']
    AbCheckbox: typeof import('./../../src/components/basic/ab-checkbox.vue')['default']
    AbContainer: typeof import('./../../src/components/ab-container.vue')['default']
    AbEditRule: typeof import('./../../src/components/ab-edit-rule.vue')['default']
    AbFoldPanel: typeof import('./../../src/components/ab-fold-panel.vue')['default']
    AbLabel: typeof import('./../../src/components/ab-label.vue')['default']
    AbPageTitle: typeof import('./../../src/components/basic/ab-page-title.vue')['default']
    AbPopup: typeof import('./../../src/components/ab-popup.vue')['default']
    AbRssItem: typeof import('./../../src/components/ab-rss-item.vue')['default']
    AbRule: typeof import('./../../src/components/ab-rule.vue')['default']
    AbSearch: typeof import('./../../src/components/basic/ab-search.vue')['default']
    AbSearchBar: typeof import('./../../src/components/ab-search-bar.vue')['default']
    AbSelect: typeof import('./../../src/components/basic/ab-select.vue')['default']
    AbSetting: typeof import('./../../src/components/ab-setting.vue')['default']
    AbSidebar: typeof import('./../../src/components/layout/ab-sidebar.vue')['default']
    AbStatus: typeof import('./../../src/components/basic/ab-status.vue')['default']
    AbStatusBar: typeof import('./../../src/components/ab-status-bar.vue')['default']
    AbSwitch: typeof import('./../../src/components/basic/ab-switch.vue')['default']
    AbTag: typeof import('./../../src/components/basic/ab-tag.vue')['default']
    AbTopbar: typeof import('./../../src/components/layout/ab-topbar.vue')['default']
    ConfigDownload: typeof import('./../../src/components/setting/config-download.vue')['default']
    ConfigExperimental: typeof import('./../../src/components/setting/config-experimental.vue')['default']
    ConfigManage: typeof import('./../../src/components/setting/config-manage.vue')['default']
    ConfigNormal: typeof import('./../../src/components/setting/config-normal.vue')['default']
    ConfigNotification: typeof import('./../../src/components/setting/config-notification.vue')['default']
    ConfigParser: typeof import('./../../src/components/setting/config-parser.vue')['default']
    ConfigPlayer: typeof import('./../../src/components/setting/config-player.vue')['default']
    ConfigProxy: typeof import('./../../src/components/setting/config-proxy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
