/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbAdd: typeof import('./basic/ab-add.vue')['default']
    AbBangumiCard: typeof import('./components/ab-bangumi-card.vue')['default']
    AbButton: typeof import('./basic/ab-button.vue')['default']
    AbCheckbox: typeof import('./basic/ab-checkbox.vue')['default']
    AbInput: typeof import('./basic/ab-input.vue')['default']
    AbPageTitle: typeof import('./basic/ab-page-title.vue')['default']
    AbSearch: typeof import('./basic/ab-search.vue')['default']
    AbSelect: typeof import('./basic/ab-select.vue')['default']
    AbSidebar: typeof import('./views/ab-sidebar.vue')['default']
    AbStatus: typeof import('./basic/ab-status.vue')['default']
    AbStatusBar: typeof import('./components/ab-status-bar.vue')['default']
    AbSwitch: typeof import('./basic/ab-switch.vue')['default']
    AbTopbar: typeof import('./views/ab-topbar.vue')['default']
    BangumiCard: typeof import('./components/bangumi-card.vue')['default']
    copy: typeof import('./basic/ab-switch copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
